format = """
$directory\
$git_branch$git_status\
$c$dart$elixir$elm$golang$haskell$java$julia$nim$nodejs$python$rust\
$docker_context\
$battery$character
[ > ]()
"""

#[ ](fg:#f7f3ee bg:#f7f3ee)\
# [aws]
# symbol = "îŒ½ "

# [azure]
# symbol = "îŒ½ "

[battery]
full_symbol = "ó°¹ "
charging_symbol = "ó°‚„ "
discharging_symbol = "ó°¾ "
unknown_symbol = "ó°‚‘ "
empty_symbol = "ó°‚ "
format = "[ $symbol$percentage ](fg:#5b5143 bg:#f7e0c3) "

[c]
symbol = "î˜"
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[character]
error_symbol = "âœ•"
success_symbol = "âœ“"
# format = '[ $symbol ](fg:#5b5143 bg:#f7e0c3) '
format = '[ $symbol ](fg:#465953 bg:#d2ebe3) '

[conda]
symbol = "ï„Œ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[dart]
symbol = "î˜ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[directory]
read_only = "ï ½ "
style = "fg:#614c61 bg:#f1ddf1"
format = "[ $path ]($style) "
truncation_length = 2
truncation_symbol = "â€¦/"

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol$context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[elm]
symbol = "î˜¬ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[git_branch]
symbol = "ï˜ "
style = "fg:#4c5361 bg:#dde4f2"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "fg:#4c5361 bg:#dde4f2"
format = '[$all_status$ahead_behind ]($style) '

[golang]
symbol = "î˜§ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[haskell]
symbol = "î· "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[java]
symbol = "î‰– "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[julia]
symbol = "î˜¤ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

[line_break]
disabled = false

# [memory_usage]
# symbol = "ï¡š "

[nim]
symbol = "ïš¤ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

# [nix_shell]
# symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

# [package]
# symbol = "ï£– "

[python]
symbol = "îˆµ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

# [spack]
# symbol = "ğŸ…¢ "

[rust]
symbol = "î¨ "
style = "fg:#525643 bg:#e2e9c1"
format = '[ $symbol($version) ]($style) '

# Not implemented

# aws
# azure
# buf
# bun
# cmake
# cobol / gnucobol
# command duration
# container
# crystal
# daml
# deno
# dotnet
# environment variable
# erlang
# fill
# gcloud
# git commit
# git state
# git metrics
# helm
# hostname
# jobs
# kotlin
# kubernetes
# line break
# local ip
# lua
# memory usage
# mercurial branch
# nix shell
# ocaml
# openstack
# package version
# perl
# php
# pulumi
# purescript
# r
# raku
# red
# ruby
# scala
# shell
# shlvl
# singularity
# spack
# status
# sudo
# swift
# terraform
# time
# username
# vagrant
# v
# vcsh
# zig
# custom commands
