[colors]
ansi = [
  '#35424c',
  '#b45648',
  '#6caa71',
  '#c4ac62',
  '#6d96b4',
  '#bd7bcd',
  '#7ccbcd',
  '#dee5eb',
]
brights = [
  '#475c6d',
  '#df6c5a',
  '#79be7e',
  '#e5c872',
  '#67b5ed',
  '#d389e5',
  '#84dde0',
  '#e5eef5',
]

# background = '#2c2d32'
background = '#323338'
# background = '#1f2531'
foreground = '#e6e6e6'

# compose_cursor = '#b6b6b5'
cursor_fg = '#1f2531'
cursor_bg = '#9c9c9c'
# cursor_border = '#605a52'

selection_fg = '#e6e6e6'
selection_bg = '#334e5e'

scrollbar_thumb = '#ff0000'
split = '#dcd3c6'

[colors.indexed]

# [colors.tab_bar]
# background = '#e4ddd2'

# [colors.tab_bar.active_tab]
# bg_color = '#f7f3ee'
# fg_color = '#605a52'

# [colors.tab_bar.inactive_tab]
# bg_color = '#e4ddd2'
# fg_color = '#605a52'

# [colors.tab_bar.inactive_tab_hover]
# bg_color = '#605a52'
# fg_color = '#f7f3ee'

# [colors.tab_bar.new_tab]
# bg_color = '#f7f3ee'
# fg_color = '#605a52'

# [colors.tab_bar.new_tab_hover]
# bg_color = '#605a52'
# fg_color = '#f7f3ee'

[metadata]
name = 'clear dark'
