# Vesper
[colors]
foreground = "#ffffff"
background = "#101010"
cursor_bg = "#acb1ab"
cursor_border = "#acb1ab"
cursor_fg = "#ffffff"
selection_bg = "#988049"
selection_fg = "#b9beb8"

ansi = ["#101010","#f5a191","#90b99f","#e6b99d","#aca1cf","#e29eca","#ea83a5","#a0a0a0"]
brights = ["#7e7e7e","#ff8080","#99ffe4","#ffc799","#b9aeda","#ecaad6","#f591b2","#ffffff"]


# [colors]
# foreground = "#c9c7be"
# background = "#101010"
# cursor_bg = "#c9c7be"
# cursor_border = "#c9c7be"
# cursor_fg = "#101010"
# selection_bg = "#404040"
# selection_fg = "#ffffff"

# ansi = [
#   "#1c1c1c",
#   "#ff6c60",
#   "#a8ff60",
#   "#ffffb6",
#   "#96cbfe",
#   "#ff73fd",
#   "#c6c5fe",
#   "#eeeeee"
# ]
# brights = [
#   "#3a3a3a",
#   "#ffb6b0",
#   "#ceffac",
#   "#ffffcc",
#   "#b5dcff",
#   "#ff9cfe",
#   "#dfdffe",
#   "#ffffff"
# ]
